package analyzer

import (
	"fmt"
	"html"
	"strings"
	"time"

	"pad-analyzer/internal/models"
)

func GenerateHTMLReport(report *models.AnalysisReport) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Analysis Report — `)
	sb.WriteString(html.EscapeString(report.FlowID))
	sb.WriteString(`</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px; }
  .container { max-width: 960px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 8px; }
  .meta { color: #94a3b8; font-size: 0.85rem; margin-bottom: 24px; }
  .health { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-weight: 600; font-size: 0.9rem; margin-bottom: 20px; }
  .health-good { background: #065f46; color: #6ee7b7; }
  .health-warn { background: #713f12; color: #fbbf24; }
  .health-bad  { background: #7f1d1d; color: #fca5a5; }
  .stats { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
  .stat { background: #1e293b; border-radius: 8px; padding: 16px 20px; flex: 1; min-width: 120px; }
  .stat-label { font-size: 0.75rem; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }
  .stat-value { font-size: 1.5rem; font-weight: 700; margin-top: 4px; }
  .stat-value.errors { color: #f87171; }
  .stat-value.warnings { color: #fbbf24; }
  .stat-value.info { color: #60a5fa; }
  .stat-value.health { color: #34d399; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th { text-align: left; padding: 10px 12px; background: #1e293b; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; border-bottom: 1px solid #334155; }
  td { padding: 10px 12px; border-bottom: 1px solid #1e293b; font-size: 0.875rem; }
  tr:hover td { background: #1e293b; }
  .severity { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
  .severity-error { background: #7f1d1d; color: #fca5a5; }
  .severity-warning { background: #713f12; color: #fde68a; }
  .severity-info { background: #1e3a5f; color: #93c5fd; }
  .category { color: #94a3b8; font-size: 0.75rem; }
  .suggestion { color: #6ee7b7; font-size: 0.8rem; margin-top: 2px; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #334155; color: #64748b; font-size: 0.75rem; }
  @media print { body { background: #fff; color: #000; } .stat { border: 1px solid #ddd; } th { background: #f1f5f9; } }
</style>
</head>
<body>
<div class="container">
`)

	sb.WriteString(fmt.Sprintf("<h1>Flow Analysis: %s</h1>\n", html.EscapeString(report.FlowID)))
	sb.WriteString(fmt.Sprintf("<div class=\"meta\">Flow ID: %s &middot; Generated: %s</div>\n",
		html.EscapeString(report.FlowID),
		time.Now().Format("2006-01-02 15:04:05")))

	if report.Metrics != nil {
		hs := report.Metrics.HealthScore
		cls := "health-good"
		if hs < 50 {
			cls = "health-bad"
		} else if hs < 75 {
			cls = "health-warn"
		}
		sb.WriteString(fmt.Sprintf("<div class=\"health %s\">Health Score: %d/100</div>\n", cls, hs))
	}

	sb.WriteString(`<div class="stats">`)
	sb.WriteString(fmt.Sprintf(`<div class="stat"><div class="stat-label">Errors</div><div class="stat-value errors">%d</div></div>`, report.Stats.Errors))
	sb.WriteString(fmt.Sprintf(`<div class="stat"><div class="stat-label">Warnings</div><div class="stat-value warnings">%d</div></div>`, report.Stats.Warnings))
	sb.WriteString(fmt.Sprintf(`<div class="stat"><div class="stat-label">Info</div><div class="stat-value info">%d</div></div>`, report.Stats.Info))
	total := report.Stats.Errors + report.Stats.Warnings + report.Stats.Info
	sb.WriteString(fmt.Sprintf(`<div class="stat"><div class="stat-label">Total</div><div class="stat-value">%d</div></div>`, total))
	sb.WriteString(`</div>`)

	if len(report.Findings) > 0 {
		sb.WriteString(`<h2 style="font-size:1.1rem; margin-bottom:8px;">Findings</h2>
<table>
<thead><tr><th>Severity</th><th>Category</th><th>Rule</th><th>Block</th><th>Message</th></tr></thead>
<tbody>
`)
		for _, f := range report.Findings {
			sevClass := "severity-" + strings.ToLower(string(f.Severity))
			sb.WriteString(fmt.Sprintf(
				`<tr><td><span class="severity %s">%s</span></td><td><span class="category">%s</span></td><td>%s</td><td>%s</td><td>%s</td></tr>`+"\n",
				sevClass,
				html.EscapeString(string(f.Severity)),
				html.EscapeString(f.Category),
				html.EscapeString(f.RuleID),
				html.EscapeString(f.BlockID),
				html.EscapeString(f.Title),
			))
		}
		sb.WriteString(`</tbody></table>`)
	} else {
		sb.WriteString(`<p style="color:#34d399; margin-top:16px;">No findings. Flow looks clean!</p>`)
	}

	sb.WriteString(fmt.Sprintf(`<div class="footer">Generated by PAD Analyzer &middot; %d rules executed &middot; %d blocks analyzed</div>`,
		report.Stats.RulesRun, report.Stats.BlocksAnalyzed))
	sb.WriteString(`</div></body></html>`)

	return sb.String()
}

func GenerateBatchHTMLReport(batch *models.BatchAnalysis) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Batch Analysis Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px; }
  .container { max-width: 1100px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 8px; }
  .meta { color: #94a3b8; font-size: 0.85rem; margin-bottom: 20px; }
  .stats { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
  .stat { background: #1e293b; border-radius: 8px; padding: 16px 20px; flex: 1; min-width: 100px; }
  .stat-label { font-size: 0.75rem; color: #94a3b8; text-transform: uppercase; }
  .stat-value { font-size: 1.4rem; font-weight: 700; margin-top: 4px; }
  .flow-card { background: #1e293b; border-radius: 8px; padding: 16px 20px; margin-bottom: 12px; }
  .flow-card h3 { font-size: 1rem; margin-bottom: 4px; }
  .flow-card .flow-meta { color: #94a3b8; font-size: 0.8rem; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.7rem; font-weight: 600; margin-left: 8px; }
  .badge-error { background: #7f1d1d; color: #fca5a5; }
  .badge-warning { background: #713f12; color: #fde68a; }
  @media print { body { background: #fff; color: #000; } }
</style>
</head>
<body><div class="container">
`)

	sb.WriteString("<h1>Batch Analysis Report</h1>\n")
	sb.WriteString(fmt.Sprintf("<div class=\"meta\">%d flows &middot; %dms duration &middot; Generated: %s</div>\n",
		batch.TotalFlows, batch.DurationMs, time.Now().Format("2006-01-02 15:04:05")))

	sb.WriteString(`<div class="stats">`)
	sb.WriteString(fmt.Sprintf(`<div class="stat"><div class="stat-label">Flows</div><div class="stat-value">%d</div></div>`, batch.TotalFlows))
	sb.WriteString(fmt.Sprintf(`<div class="stat"><div class="stat-label">Errors</div><div class="stat-value" style="color:#f87171">%d</div></div>`, batch.TotalErrors))
	sb.WriteString(fmt.Sprintf(`<div class="stat"><div class="stat-label">Warnings</div><div class="stat-value" style="color:#fbbf24">%d</div></div>`, batch.TotalWarnings))
	sb.WriteString(fmt.Sprintf(`<div class="stat"><div class="stat-label">Avg Health</div><div class="stat-value" style="color:#34d399">%.0f</div></div>`, batch.AvgHealthScore))
	sb.WriteString(`</div>`)

	for _, r := range batch.Results {
		badges := ""
		if r.Report != nil {
			if r.Report.Stats.Errors > 0 {
				badges += fmt.Sprintf(`<span class="badge badge-error">%d errors</span>`, r.Report.Stats.Errors)
			}
			if r.Report.Stats.Warnings > 0 {
				badges += fmt.Sprintf(`<span class="badge badge-warning">%d warnings</span>`, r.Report.Stats.Warnings)
			}
		}
		sb.WriteString(fmt.Sprintf(`<div class="flow-card"><h3>%s%s</h3>`, html.EscapeString(r.FlowName), badges))
		if r.Error != "" {
			sb.WriteString(fmt.Sprintf(`<div class="flow-meta" style="color:#f87171;">Error: %s</div>`, html.EscapeString(r.Error)))
		} else if r.Report != nil {
			hs := 0
			if r.Report.Metrics != nil {
				hs = r.Report.Metrics.HealthScore
			}
			sb.WriteString(fmt.Sprintf(`<div class="flow-meta">Health: %d/100 &middot; %d findings</div></div>`, hs, len(r.Report.Findings)))
		}
	}

	sb.WriteString(`</div></body></html>`)
	return sb.String()
}
