/** @type {import('tailwindcss').Config} */
export default {
  // Test files are excluded: classNames in fixtures/mocks would otherwise be
  // extracted as production utilities (pure CSS bloat in the built sheet).
  content: ['./index.html', './src/**/*.{ts,tsx}', '!./src/**/*.test.*'],
  darkMode: ['class', '[data-theme="dark"], [data-theme="midnight"], [data-theme="warm"], [data-theme="tokyo-night"], [data-theme="one-dark"], [data-theme="dracula"], [data-theme="nord"], [data-theme="gruvbox-dark"], [data-theme="catppuccin-mocha"], [data-theme="rose-pine"], [data-theme="rose-pine-moon"], [data-theme="github-dark"], [data-theme="kanagawa"], [data-theme="everforest"]'],
  theme: {
    extend: {
      colors: {
        surface: {
          0: 'var(--surface-0)',
          1: 'var(--surface-1)',
          2: 'var(--surface-2)',
          3: 'var(--surface-3)',
          4: 'var(--surface-4)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          strong: 'var(--border-strong)',
          focus: 'var(--border-focus)',
        },
        brand: {
          50: 'var(--brand-50)',
          100: 'var(--brand-100)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          foreground: 'var(--brand-foreground)',
        },
        block: {
          action: 'var(--block-action)',
          loop: 'var(--block-loop)',
          condition: 'var(--block-condition)',
          subflow: 'var(--block-subflow)',
          error: 'var(--block-error)',
          comment: 'var(--block-comment)',
          variable: 'var(--block-variable)',
          string: 'var(--block-string)',
          wait: 'var(--block-wait)',
          'action-bg':    'var(--block-action-bg)',
          'loop-bg':      'var(--block-loop-bg)',
          'condition-bg': 'var(--block-condition-bg)',
          'subflow-bg':   'var(--block-subflow-bg)',
          'error-bg':     'var(--block-error-bg)',
          'comment-bg':   'var(--block-comment-bg)',
          'variable-bg':  'var(--block-variable-bg)',
          'string-bg':    'var(--block-string-bg)',
          'wait-bg':      'var(--block-wait-bg)',
        },
        semantic: {
          success: 'var(--success)',
          warning: 'var(--warning)',
          error: 'var(--error)',
          info: 'var(--info)',
        },
      },
      borderColor: {
        DEFAULT: 'var(--border-default)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs: ['11px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '18px' }],
        base: ['15px', { lineHeight: '22px' }],
        lg: ['17px', { lineHeight: '24px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em' }],
        '3xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em' }],
      },
      spacing: {
        0.5: 'var(--space-0.5)',
        1: 'var(--space-1)',
        1.5: 'var(--space-1.5)',
        2: 'var(--space-2)',
        2.5: 'var(--space-2.5)',
        3: 'var(--space-3)',
        3.5: 'var(--space-3.5)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
      },
      zIndex: {
        base: 'var(--z-base)',
        raised: 'var(--z-raised)',
        overlay: 'var(--z-overlay)',
        sticky: 'var(--z-sticky)',
        modal: 'var(--z-modal)',
        tooltip: 'var(--z-tooltip)',
        toast: 'var(--z-toast)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        glow: 'var(--shadow-glow)',
        'glow-error': 'var(--shadow-glow-error)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
      },
      backdropBlur: {
        glass: '16px',
      },
    },
  },
  plugins: [],
};
