package models

// Patch describes a textual edit to a flow's source text. Edits are LINE-BASED
// (1-based line numbers matching Block.LineNumber) and apply to the RAW source
// text — never to a re-serialization of the parsed document (which would lose
// PAD's original parameter order, quoting, and multi-line values). After
// applying, the patched text is re-parsed to validate structure and re-analyzed
// to confirm the finding is resolved.
//
// Patches are intentionally minimal and structural: insert comment lines, wrap
// a block in an error handler, etc. They are generated by AutoFixers (one per
// deterministic fix) and reviewed by the user before apply.
type Patch struct {
	// File is the source file within a multi-file flow ("" for a single-file
	// flow, or the subflow file name). Patches target one file.
	File string    `json:"file,omitempty"`
	Ops  []PatchOp `json:"ops"`
}

// PatchOp is one line-level textual edit. The Kind discriminates the op; only
// the fields relevant to that kind are set.
//
// Kind "insert": insert Lines before BeforeLine (1-based). BeforeLine=1 inserts
// at the very top; BeforeLine=N inserts between lines N-1 and N; BeforeLine=0
// (or beyond EOF) appends. Multiple inserts are applied bottom-up so earlier
// ops don't shift later ops' line targets.
//
// Kind "wrap": wrap the inclusive range [StartLine..EndLine] (1-based) with
// Header (emitted before) and Footer (emitted after), and re-indent each line
// in the range by IndentDelta 4-space levels (positive = indent more). Used to
// wrap an action in an ON BLOCK ERROR … END block: Header/Footer land at the
// block's original indent and the wrapped line(s) move one level in to become
// the handler's children. Apply-fix patches carry one op (one finding at a
// time), so multi-wrap interaction is not a concern.
//
// Kind "append": append Lines[0] to the end of line StartLine (1-based). Used
// to add a property to an action's source line in-place (e.g. ` Timeout: 30`)
// without rewriting the original line — preserves parameter order, quoting,
// and multi-line values.
//
// Kind "replace": within line StartLine (1-based), replace all occurrences of
// Old with New on that line. Used to swap a hardcoded credential literal for a
// %Variable% reference in-place — when the same secret value appears in
// multiple properties on the same line, all should be replaced.
//
// Kind "remove": delete the inclusive 1-based range [StartLine..EndLine]. Used
// to delete a block (and its descendants, when EndLine = the block's last
// descendant line) — resolves dead-code, unused-variable, redundant-action,
// duplicate-action, and disabled-block by removing the offending block
// outright. Reuses StartLine/EndLine (same range semantics as "wrap", just
// without inserting a header/footer).
type PatchOp struct {
	Kind       string   `json:"kind"`
	BeforeLine int      `json:"beforeLine,omitempty"`
	Lines      []string `json:"lines,omitempty"`
	// wrap + append + replace
	StartLine   int    `json:"startLine,omitempty"`
	EndLine     int    `json:"endLine,omitempty"`
	Header      string `json:"header,omitempty"`
	Footer      string `json:"footer,omitempty"`
	IndentDelta int    `json:"indentDelta,omitempty"`
	// replace
	Old string `json:"old,omitempty"`
	New string `json:"new,omitempty"`
}
